### ISSUE TITLE
Provide a sample using Razor class library project

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#17]
It is unclear how best to integrate BlazorBindGen within the **life cycle methods** and **options for injection of IJSRuntime** within the project file structure provided by the created Razor Class Library project

**Comment by sps014** [comment]
https://github.com/sps014/BlazorML5/tree/master/BlazorML5

**Comment by GeorgeS2019** [comment]
There is no wwwroot folder and html razor page which need to Import module.

This is only one form of possible BlazorBindGen  razor class lib use case

**Comment by sps014** [comment]
> There is no wwwroot folder and html razor page which need to Import module.
> 
> This is only one form of possible BlazorBindGen  razor class lib use case

You can use Blazor exposed Import method, which can return IJSObjectReference.

**Comment by sps014** [comment]
https://visualstudiomagazine.com/articles/2018/08/01/integrating-blazor-javascript.aspx?m=1#:~:text=Integrating%20JavaScript%20and%20Blazor%20is,tag%20that%20references%20_framework%2Fblazor.

**Comment by sps014** [comment]
Also there is no index.html in Razor

**Comment by GeorgeS2019** [comment]
When one create a new RazorClass library using template, there is wwwroot with Javascript for interoperable and a cs class for interoperability that has a constructor that injected with IJSRuntime... 

Your users need to integrate your Nuget into that starting template

**Comment by sps014** [comment]
Why can't you have a wwwroot folder with JS file , it's same, just import using Blazor exposed Import method.
In some cases js import also works there you do not need to do any tricks.

**Comment by GeorgeS2019** [comment]
The provided CS file does not inherit from the component base  class and without life cycle method for your bindgen to init from the injected IJSRuntime.

**Comment by sps014** [comment]
Cause they have their lifecycle separately managed by bindgen automatically,
You can see other sample with wwwroot folder which uses traditional import on ijsruntime
            https://github.com/sps014/FFmpegBlazor/blob/1bddff3a101a44eca61cd2b2ed6d480e07e59025/FFmpegBlazor/FFmpegFactory.cs#L37

**Comment by GeorgeS2019** [comment]
Thx..exactly what I need...👍😀
