### ISSUE TITLE
How to address the CORS policy using BlazorBindGen?

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#3]
### Question 1: how to address the CORS policy?
> Access to script at 'https://meet.jit.si/external_api.js' from origin 'https://localhost:44376' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> Unhandled exception rendering component: TypeError: Failed to fetch dynamically imported module: https://meet.jit.si/external_api.js
> System.Exception: TypeError: Failed to fetch dynamically imported module: https://meet.jit.si/external_api.js
>    at BlazorBindGen.LockHandler.HoldVoid(Int64 errH) in BlazorBindGen\Bindings\LockHandler.cs:line 17
>    at BlazorBindGen.BindGen.Import(String moduleURL) in BlazorBindGen\Bindings\BindGen.cs:line 65
>    at SampleApp.Pages.JitsiMeet.Draw() in BlazorBindGen\SampleApp\Pages\JitsiMeet.razor:line 36
>    at SampleApp.Pages.JitsiMeet.OnInitializedAsync() in BlazorBindGen\SampleApp\Pages\JitsiMeet.razor:line 23
>    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Question 2: Is there a way to handle TWO imports?
- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
- <script src="https://meet.jit.si/external_api.js"></script>

```cs
 await Import("https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js");
 await Import("https://meet.jit.si/external_api.js");
```

### Question 3: How would you make Jitsi-meet works?
Consider the fact you have demonstrated [VideoCamPage.razor](https://github.com/sps014/BlazorBindGen/blob/main/SampleApp/Pages/VideoCamPage.razor)

## [Reference ](https://github.com/malcolmswainecom/jitsi-meet-basic-web-client/blob/master/public_html/index.html)

```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://meet.jit.si/external_api.js"></script>
<script>
$(document).ready(function(){
        var domain = "meet.jit.si";
	var options = {
		roomName: "JitsiMeetAPIExample",
		width: 700,
		height: 700,
		parentNode: document.querySelector('#meet')
	}
        var api = new JitsiMeetExternalAPI(domain, options);
});
</script>

<title>Hello Node</title>
</head>
<body>
<h1>Page served from Node http-server</h1>
<div id="meet">
	meeting
</div>
<p></p>
</body>
</html>
```

```cs
@page "/jitsimeet1"

@using BlazorApp
@using BlazorBindGen
@using static BlazorBindGen.BindGen
@inject IJSRuntime runtime

<h1 style="color:white;">Page served from Node http-server</h1>
<div id="container">
    <div id="meet" @ref="canvas">meeting</div>
</div>

@code
{
    ElementReference canvas;

    JWindow win;
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Init(runtime);
        win = Window;
        await Draw();
    }

    //var domain = "meet.jit.si";
    //var options = {
    //	roomName: "JitsiMeetAPIExample",
    //	width: 700,
    //	height: 700,
    //	parentNode: document.querySelector('#meet')
    //	}
    //var api = new JitsiMeetExternalAPI(domain, options);
    async Task Draw()
    {
        await Import("https://meet.jit.si/external_api.js");
        //converting param from JS object to C# Class (Convert first to JS->JSON->C# class using automatic generators)
        var param = new JitsiInput
        {
            domain ="meet.jit.si",
            options = new JitsiOptions
            {
                   roomName = "JitsiMeetAPIExample",
		   width = 700,
		   height = 700,
		   parentNode = canvas
            }
        };
        JObjPtr _jitsi = Window.CallRef("JitsiMeetExternalAPI", param); /* js reference to jitsit */
    }

    public class JitsiOptions
    {
        public ElementReference parentNode { get; set; }
        public string roomName { get; set; }
        public int width { get; set; }
        public int height { get; set; }
    }

    public class JitsiInput
    {
        public string domain { get; set; }
        public JitsiOptions options { get; set; }
    }
}
<style>
    #container {
        margin: 0px auto;
        width: 500px;
        height: 375px;
        border: 10px #333 solid;
    }

</style>
```

**Comment by GeorgeS2019** [comment]
Close as stated in the [commit](https://github.com/sps014/BlazorBindGen/commit/05f93ca5b866f349422228ee1b4ce668c2a17a77)

**Comment by GeorgeS2019** [comment]
@sps014  Now that u have implemented Blazor Server App. Can the CORS issue discussed here be addressed.?
I have not the time yet for next two months to re-visit this issue. 

Hopefully you are aware of CORS issue facing BlazorBindGen

**Comment by sps014** [comment]
> @sps014  Now that u have implemented Blazor Server App. Can the CORS issue discussed here be addressed.?
> I have not the time yet for next two months to re-visit this issue. 
> 
> Hopefully you are aware of CORS issue facing BlazorBindGen

As stated earlier Import in BindGen is wrapper around js `import`.
Also Jitsi doesn't allow the js file to served on serverless mode.
To fix this you can download jitsi.min.js and put it in wwwroot folder and change url `await ImportAsync("_content/AppAssemblyName/jitsi.meet.js");`.

This issue originate from jitsi
https://community.jitsi.org/t/cannot-get-lib-jitsi-meet-to-work-because-of-cors/19292

**Comment by GeorgeS2019** [comment]
@sps014  Now that this repo has advanced to support blazor server app, I understand you have tight schedule, could your suggestion address CORS and eventually making Jitsi.meet.js to work?

**Comment by sps014** [comment]
> @sps014 Now that this repo has advanced to support blazor server app, I understand you have tight schedule, could your suggestion address CORS and eventually making Jitsi.meet.js to work?

I downloaded `https://meet.jit.si/external_api.js` locally and added in `index.html` file to solve CORS,
for using es6 module use
```html
<script type="module">
import * as jitsi from '../local path to js file';
console.log(jitsi);
</script>
```
![Screenshot 2022-01-20 194955](https://user-images.githubusercontent.com/45932883/150357424-b03c54ec-c180-4941-b35f-0e12adcfe7e8.png)


the above system doesn't work with blazorBindGen as blazor doesn't support ES6 module import. you have to use JS until then.
