### ISSUE TITLE
How to deal with CommonJS?

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#5]
I am curious if BlazorBindGen is ready to support CommonJS in the following use case? If not, what modifications or addition needed?

[Example App Source](https://github.com/metincansiper/chise.js-multiple-tabs-sample-app/blob/master/index.html)
[API Source](https://github.com/iVis-at-Bilkent/chise.js)

[Dependencies](https://github.com/iVis-at-Bilkent/chise.js#dependencies)

- cytoscape
- jQuery
- file-saver
- tippy.js
- sbgnviz
- lodash.isequal

[Source](https://github.com/iVis-at-Bilkent/chise.js/blob/master/package.json)
```js
    "jquery": "^2.2.4",
    "file-saver": "^2.0.2",
    "cytoscape": "iVis-at-Bilkent/cytoscape.js#master",
    "sbgnviz": "^6.0.0",
    "tippy.js": "^3.4.0"
```

```js
var sbgnviz = require('sbgnviz');
var cytoscape = require('cytoscape-for-sbgnviz');
var jQuery = require('jQuery');
var filesaver = require('file-saver');
var sbgnviz = require('sbgnviz');
var tippy = require('tippy.js');

var options = {
};

var libs = {
    cytoscape: cytoscape,
    jQuery: jQuery,
    filesaver: filesaver,
    sbgnviz: sbgnviz,
    tippy = tippy
};

// Register chise with libs
chise.register(libs);

// Create a new chise.js instance
var chiseInstance = chise(options);
```

**Comment by sps014** [comment]
```js
var sbgnviz = require('sbgnviz');
var cytoscape = require('cytoscape-for-sbgnviz');
var jQuery = require('jQuery');
var filesaver = require('file-saver');
var sbgnviz = require('sbgnviz');
var tippy = require('tippy.js');
```
require() is not a part of JavaScript standard and is not supported by browsers out of the box, it is the node.js module system. 
You can use something like [Browserify](https://browserify.org/)


For any custom advanced scenario you always have power of JS in BlazorBindGen suppose you want to  do some stuff you are not able to from C# in that case you can create a JS file in wwwroot and add reference <script> that file in `index.html`

now write your JS code 
```js
var sbgnviz = require('sbgnviz');
var cytoscape = require('cytoscape-for-sbgnviz');
var jQuery = require('jQuery');
var filesaver = require('file-saver');
var sbgnviz = require('sbgnviz');
var tippy = require('tippy.js');

window.Init=()=>
{
      var options = {};

      var libs = {
      cytoscape: cytoscape,
      jQuery: jQuery,
      filesaver: filesaver,
      sbgnviz: sbgnviz,
      tippy = tippy
      };

     // Register chise with libs
     chise.register(libs);

      // Create a new chise.js instance
     var chiseInstance = chise(options);
}
```

On C# side you can invoke it as

```cs
    Window.CallVoid("Init");
```

**Comment by GeorgeS2019** [comment]
Using the example above

[bundle.js](https://github.com/metincansiper/chise.js-multiple-tabs-sample-app/blob/master/app/bundle.js) has been provided.

Which has been created based on[ **index.js**](https://github.com/metincansiper/chise.js-multiple-tabs-sample-app/blob/master/app/index.js)

## Questions

To use chise.js API

I am thinking along this way (based on the **index.js**)

For example, create a new file : **start.js**

```js
var sbgnviz = require('sbgnviz');
var chise = require('chise');
var filesaverjs = require('filesaverjs');
var jQuery = $ = require('jquery');
var cytoscape = require('cytoscape');

// Get cy extension instances
var cyPanzoom = require('cytoscape-panzoom');
// var cyQtip = require('cytoscape-qtip');
var cyCoseBilkent = require('cytoscape-cose-bilkent');
var cyUndoRedo = require('cytoscape-undo-redo');
var cyClipboard = require('cytoscape-clipboard');
var cyContextMenus = require('cytoscape-context-menus');
var cyExpandCollapse = require('cytoscape-expand-collapse');
var cyEdgeBendEditing = require('cytoscape-edge-bend-editing');
var cyViewUtilities = require('cytoscape-view-utilities');

// Register cy extensions
cyPanzoom( cytoscape, $ );
// cyQtip( cytoscape, $ );
cyCoseBilkent( cytoscape );
cyUndoRedo( cytoscape );
cyClipboard( cytoscape, $ );
cyContextMenus( cytoscape, $ );
cyExpandCollapse( cytoscape, $ );
cyEdgeBendEditing( cytoscape, $ );
cyViewUtilities( cytoscape, $ );

// Libraries to pass sbgnviz
var libs = {};

libs.filesaverjs = filesaverjs;
libs.jQuery = jQuery;
libs.cytoscape = cytoscape;
libs.sbgnviz = sbgnviz;

$(document).ready(function ()
{
  chise.register(libs);

  // Undoable flag to be passed to the extensions
  var undoable = true;
}
```

Then create a bundle.js out of start.js

Instead of including this code into start.js

```js
var ch1 = window.ch1 = chise({
    networkContainerSelector: '#sbgn-network-container1',
    // whether to fit label to nodes
    fitLabelsToNodes: function () {
      return false;
    },
    // dynamic label size it may be 'small', 'regular', 'large'
    dynamicLabelSize: function () {
      return 'regular';
    },
    // percentage used to calculate compound paddings
    compoundPadding: function () {
      return 10;
    },
    undoable: undoable
  });

```

Try doing the above in Blazor WASM app

Use BlazorBindGen to importAsync
`await ImportAsync("https://localhost:xxxxx/app/bundle.js");`

JObjPtr _ch1 = Window.CallRef("chise", param); /* js reference to chise  as var ch1 = window.ch1 = chise*/

Where param will be BlazorBindGen version of 
```js
networkContainerSelector: '#sbgn-network-container1',
    // whether to fit label to nodes
    fitLabelsToNodes: function () {
      return false;
    },
    // dynamic label size it may be 'small', 'regular', 'large'
    dynamicLabelSize: function () {
      return 'regular';
    },
    // percentage used to calculate compound paddings
    compoundPadding: function () {
      return 10;
    },
    undoable: undoable
```

Once I have JObjPtr **_ch1**

I could proceed with the rest of **index.js**

```js
ch1.loadSample('sample2.xml', 'app/samples/');
ch1.getCy().undoRedo();
```

Please advice :-) Is this feasible through BlazorBindGen ?

**Comment by sps014** [comment]
looks feasible, only limitation of blazor bindGen , I know is object construction with `JObjPtr` with nesting 
eg.
```js
let obj={
     a:"abc",
     b:jptr
} 
```


now when you pass this obj js side , it wont have proper value for b.
i can solve this but if i look at each property on pass to js , performance will be degraded


#### Workaround

to deal with this you can do
```cs

var obj=Window.Construct("Object");
obj.SetProp("a","abc");
obj.SetPropRef("b",jptr);
```
````

**Comment by GeorgeS2019** [comment]
`var jQuery = $ = libs.jQuery;  `
Any [code ](https://github.com/metincansiper/chise.js-multiple-tabs-sample-app/blob/2cfce6e3f99b06040c7a60f127548937d73e7c55/app/index.js#L4)with $ will throw error when BlazorBindGen parse it
- [example1 ](https://github.com/metincansiper/chise.js-multiple-tabs-sample-app/blob/2cfce6e3f99b06040c7a60f127548937d73e7c55/app/index.js#L19)

I can replace $ with jQuery. 

However, this mean all dependency library with $ when parsing the created bundle.js

**Comment by sps014** [comment]
[IJSRuntime](https://source.dot.net/#Microsoft.JSInterop/JSRuntime.cs,25ea88e483ca3a98) underneath uses JSon Serializer `$` causes some issues in interop.
Unfortunately Blazor Interop only support recent ECMA standards. Looking at IJSRuntime source it can be made to perform that task, I don't think Blazor Team will be interested in doing so. We need more people to raise this issue.
[This](https://github.com/sps014/BlazorBindGen/issues/5#issuecomment-955184176) is the only workaround I see.

**Comment by GeorgeS2019** [comment]
Only [ECMA standard](https://github.com/dotnet/AspNetCore.Docs/issues/20461#issuecomment-726071748) has been discussed before. However, we need[ good use cases to support **CJS format**](https://github.com/dotnet/AspNetCore.Docs/issues/20461#issue-739460994)

**Comment by sps014** [comment]
I am not sure what i can do in this regard.
If anything i could do to help you , I will be more than happy.

**Comment by GeorgeS2019** [comment]
If you have time, take a look of this[ .NET approach to CommonJS](https://github.com/tylerjwatson/Jint.CommonJS)

**Comment by GeorgeS2019** [comment]
[How to convert CommonJS require into ES6+ import?](https://stackoverflow.com/questions/68985334/how-to-convert-commonjs-require-into-es6-import)

built with webpack and ends with `module.exports = __webpack_exports__; `

babel outputs modules **not in ES Module type.** So you **can't import module that is not exports something in ES modules style**. 

Reference: [ CommonJS vs AMD vs RequireJS vs ES6 Modules ](https://medium.com/computed-comparisons/commonjs-vs-amd-vs-requirejs-vs-es6-modules-2e814b114a0b)
