### ISSUE TITLE
WebAssembly app does not run

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#6]

**Comment by GeorgeS2019** [comment]
I can get ther server app works, not the web. Interesting

**Comment by GeorgeS2019** [comment]
![image](https://user-images.githubusercontent.com/49812372/174109820-0b1b7521-5e9f-4a38-bcc1-2b1be7aab2fb.png)

**Comment by GeorgeS2019** [comment]
I created a new BlazorWASMapp based on provided template.  I reference BlazorBindGen and transfer the content of Index.razor from the SampleApp to the new App. It works!  Something in the SampleApp is preventing it from running in VS2022

**Comment by sps014** [comment]
> I created a new BlazorWASMapp based on provided template.  I reference BlazorBindGen and transfer the content of Index.razor from the SampleApp to the new App. It works!  Something in the SampleApp is preventing it from running in VS2022
> 
> ![image](https://user-images.githubusercontent.com/49812372/174155079-311ae104-51c3-4762-8a97-6e19e2e9b925.png)
> 
> ## Question
> Any idea why I have this **browserLink**?

Browser link is hot reload web socket connection.
Vs tooling for hot reload is kinda rough.
